module.exports = {
	selectedValues: {
		recipients: {
			parnja: "Парня",
			devushku: "Девушку",
			mamu: "Маму",
			papu: "Папу",
			brata: "Брата",
			sestru: "Сестру",
			druga: "Друга",
			podrugu: "Подругу",
			babushku: "Бабушку",
			dedushku: "Дедушку",
			kollegu: "Коллегу",
		},
		holidays: {
			"s-dnem-rozhdeniya": "c Днем рождения",
			"s-yubileem": "с Юбилеем",
			"s-1-aprelya": "1 апреля",
			"s-9-maya-dnem-pobedy-v-vov": "9 мая, день победы в ВОВ",
			"s-novym-godom": "Новый год",
			"s-rozhdestvom": "Рождество",
			"s-8-marta": "8 марта",
			"s-dnem-zashitnika-otechestva": "День защитника Отечества",
			"s-dnem-rossii": "День России",
			"s-dnem-vlyublennih": "День влюбленных",
			"s-dnem-materi": "День матери",
			"s-godovshinoj-svavadby": "Годовщина свадьбы",
			"so-svadboj": "Свадьба",
			"s-vypusknym-v-shkole": "Выпускной в школе",
			"s-vypussknym-v-universitete": "Выпускной в университете",
		},
		professions: {
			"ne-vazhno": "Не важно",
			administrator: "Администратор",
			akter: "Актер",
			aitishnik: "Айтишник",
			barmen: "Бармен",
			biznesmen: "Бизнесмен",
			bloger: "Блогер",
			buhgalter: "Бухгалтер",
			voditel: "Водитель",
			voennyy: "Военный",
			vrach: "Врач",
			direktor: "Директор",
			dizayner: "Дизайнер",
			zhurnalist: "Журналист",
			inzhener: "Инженер",
			kriptovaljutchik: "Криптовалютчик",
			menedzher: "Менеджер",
			ohrannik: "Охранник",
			perevodchik: "Переводчик",
			predprinimatel: "Предприниматель",
			prodavets: "Продавец",
			programmist: "Программист",
			razrabotchik: "Разработчик",
			sekretar: "Секретарь",
			taksist: "Таксист",
			uchitel: "Учитель",
			fotograf: "Фотограф",
		},
		style: {
			smeshnoje: "Смешное и остроумное",
			romantichnoe: "Романтичное",
			formalnoje: "Формальное и красивое",
		},
	},
};
